### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by cameron** [marcorinck/ngStart#24]
Haven't dug into this at all, but it happened in a fresh docker container from an ubuntu image. Not the first time I've seen grunt version conflicts, either.  

```
npm http GET https://registry.npmjs.org/karma
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-contrib-clean
npm http GET https://registry.npmjs.org/grunt-contrib-copy
npm http GET https://registry.npmjs.org/grunt-contrib-compress
npm http GET https://registry.npmjs.org/grunt-contrib-jshint
npm http GET https://registry.npmjs.org/grunt-contrib-connect
npm http GET https://registry.npmjs.org/grunt-contrib-watch
npm http GET https://registry.npmjs.org/grunt-contrib-cssmin
npm http GET https://registry.npmjs.org/grunt-karma
npm http GET https://registry.npmjs.org/grunt-requirejs
npm http GET https://registry.npmjs.org/grunt-exec
npm http GET https://registry.npmjs.org/grunt-data-uri
npm http GET https://registry.npmjs.org/grunt-targethtml
npm http GET https://registry.npmjs.org/grunt-manifest
npm http GET https://registry.npmjs.org/grunt-release
npm http GET https://registry.npmjs.org/license-checker
npm http GET https://registry.npmjs.org/matchdep
npm http 200 https://registry.npmjs.org/grunt-contrib-clean

npm ERR! Error: No compatible version found: grunt-contrib-clean@'>=0.5.0- <0.6.0-'
npm ERR! Valid install targets:
npm ERR! ["0.1.0","0.2.0","0.3.0","0.3.1","0.3.2","0.4.0-a"]
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:488:10)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:438:17)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /ngStart/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.8.0-19-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /ngStart
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message No compatible version found: grunt-contrib-clean@'>=0.5.0- <0.6.0-'
npm ERR! message Valid install targets:
npm ERR! message ["0.1.0","0.2.0","0.3.0","0.3.1","0.3.2","0.4.0-a"]
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /ngStart/npm-debug.log
npm not ok
```

**Comment by marcorinck** [comment]
that seems to be a problem with the npm repository, as there is definitely a 0.5 version of grunt-contrib-clean: 

```
e:\>npm info grunt-contrib-clean

{ name: 'grunt-contrib-clean',
  description: 'Clean files and folders.',
  'dist-tags': { latest: '0.5.0', devel: '0.4.0-rc5' },
  versions:
   [ '0.1.0',
     '0.2.0',
     '0.3.0',
     '0.3.1',
     '0.3.2',
     '0.4.0-a',
     '0.4.0-rc5',
     '0.4.0-rc6',
     '0.4.0',
     '0.4.1',
     '0.5.0' ],
....
```

Can you try it again?

**Comment by blindMoe** [comment]
Any word on this?  Running into the same issue

**Comment by blindMoe** [comment]
This was due to using an older node version.. using 0.10.4 fixed it
